[package]
autotests = false
edition = "2018"
name = "seq"
publish = false
version = "0.0.0"
[dependencies]
proc-macro2 = "*"
quote = "*"
syn = {version="*", features=["full"]}

[dev-dependencies]
trybuild = "1.0"

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/progress.rs"
