[package]
autotests = false
edition = "2018"
name = "derive_builder"
publish = false
version = "0.0.0"
[dependencies]
quote = "*"
syn = "*"

[dev-dependencies]
trybuild = "1.0"

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/progress.rs"
